[package]
name = "robust-lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40.0", features = ["full"] }
tower-lsp = "0.20.0"
tree-sitter = "0.23.0"
tree-sitter-c-sharp = "0.23.0"
tree-sitter-yaml = "0.6.1"

[build-dependencies]
cc = "1.1.23"

[profile.dev]
debug = 2
build-override.debug = 2
